from quantlab_ml.contracts.common import (
    InvalidActionMaskSemantics,
    LineagePointer,
    NumericBand,
    TimeRange,
)
from quantlab_ml.contracts.dataset import (
    DatasetSpec,
    NormalizedMarketEvent,
    REQUIRED_FIELDS_BY_STREAM,
    StreamFieldCatalog,
    WalkForwardSpec,
)
from quantlab_ml.contracts.event_token_cache import (
    BBO_PAYLOAD_SCHEMA_ID,
    EVENT_TOKEN_CACHE_DIAGNOSTICS_FILENAME,
    EVENT_TOKEN_CACHE_DIAGNOSTICS_FORMAT_VERSION,
    EVENT_TOKEN_CACHE_DIRNAME,
    EVENT_TOKEN_CACHE_FORMAT_VERSION,
    EVENT_TOKEN_CACHE_MANIFEST_FILENAME,
    EVENT_TOKEN_CACHE_SUMMARY_FILENAME,
    EVENT_TOKENIZER_VERSION,
    EVENT_WINDOW_CONTRACT_VERSION,
    TRADE_PAYLOAD_SCHEMA_ID,
    EventTokenCacheDiagnosticsManifest,
    EventTokenCacheManifest,
    EventTokenCachePayloadStatus,
    EventTokenCacheRetentionReceipt,
    EventTokenReplayRow,
    EventTokenRowWindowStats,
    EventTokenShardManifest,
    EventTokenSplitDiagnostics,
    EventTokenSplitManifest,
)
from quantlab_ml.contracts.evaluation import EvaluationBoundary, EvaluationReport, PolicyScore
from quantlab_ml.contracts.learning_surface import (
    ACTION_SPACE_VERSION_V1,
    ACTION_SPACE_VERSION_V2_PHASE1A,
    ActionChoice,
    ActionFeasibilitySurface,
    ActionSpaceSpec,
    DerivedChannel,
    DerivedSurface,
    FeasibilityCell,
    ObservationContext,
    ObservationSchema,
    PolicyState,
    RawScaleTensor,
    ScaleSpec,
    SplitArtifact,
    SplitWindow,
    TrajectoryBundle,
    TrajectoryRecord,
    TrajectorySpec,
    TrajectoryStep,
    WalkForwardFold,
)
from quantlab_ml.contracts.policies import (
    ACTION_SPACE_VERSION,
    DERIVED_CHANNEL_TARGET_PLACEHOLDER,
    DYNAMIC_TARGET_ASSET,
    EXECUTION_INTENT_SCHEMA_VERSION,
    JOINT_ACTION_VOCABULARY_VERSION_PHASE1A,
    LEGACY_POLICY_ARTIFACT_SCHEMA_VERSION,
    OBSERVATION_SCHEMA_VERSION,
    POLICY_ARTIFACT_SCHEMA_VERSION,
    POLICY_STATE_FEATURE_VERSION_PHASE1A,
    STRICT_RUNTIME_CONTRACT_VERSION,
    DerivedChannelTemplate,
    ExecutionIntent,
    InferenceArtifactExport,
    ExecutorMetadata,
    ExecutorPolicyExport,
    OpaquePolicyPayload,
    PolicyArtifact,
    RuntimeMetadata,
    StrictRuntimeContract,
)
from quantlab_ml.contracts.registry import (
    ComparisonReport,
    ContinuityAuditSummary,
    ContinuityCloseoutRecord,
    CoverageStats,
    PaperSimEvidenceRecord,
    PromotionDecisionRecord,
    PromotionEvidence,
    RegistryIndex,
    RegistryRecord,
    ReproducibilityMetadata,
    ScoreSnapshot,
    SearchBudgetSummary,
    SplitEvidence,
)
from quantlab_ml.contracts.rewards import (
    ActionReward,
    RewardContext,
    RewardEventSpec,
    RewardSnapshot,
    RewardTimeline,
    VenueExecutionRef,
)

from quantlab_ml.contracts.manifest import (
    TRAJECTORY_STREAMING_FORMAT_VERSION,
    TrajectoryManifest,
    TrajectorySplitStats,
)

# NOTE: contracts.compat intentionally excluded from public API.
# Import it directly from quantlab_ml.contracts.compat when needed.

__all__ = [
    # common
    "InvalidActionMaskSemantics",
    "LineagePointer",
    "NumericBand",
    "TimeRange",
    # dataset
    "DatasetSpec",
    "NormalizedMarketEvent",
    "REQUIRED_FIELDS_BY_STREAM",
    "StreamFieldCatalog",
    "WalkForwardSpec",
    # event token cache
    "BBO_PAYLOAD_SCHEMA_ID",
    "EVENT_TOKEN_CACHE_DIAGNOSTICS_FILENAME",
    "EVENT_TOKEN_CACHE_DIAGNOSTICS_FORMAT_VERSION",
    "EVENT_TOKEN_CACHE_DIRNAME",
    "EVENT_TOKEN_CACHE_FORMAT_VERSION",
    "EVENT_TOKEN_CACHE_MANIFEST_FILENAME",
    "EVENT_TOKEN_CACHE_SUMMARY_FILENAME",
    "EVENT_TOKENIZER_VERSION",
    "EVENT_WINDOW_CONTRACT_VERSION",
    "TRADE_PAYLOAD_SCHEMA_ID",
    "EventTokenCacheDiagnosticsManifest",
    "EventTokenCacheManifest",
    "EventTokenCachePayloadStatus",
    "EventTokenCacheRetentionReceipt",
    "EventTokenReplayRow",
    "EventTokenRowWindowStats",
    "EventTokenShardManifest",
    "EventTokenSplitDiagnostics",
    "EventTokenSplitManifest",
    # evaluation
    "EvaluationBoundary",
    "EvaluationReport",
    "PolicyScore",
    # learning_surface
    "ActionChoice",
    "ActionFeasibilitySurface",
    "ACTION_SPACE_VERSION_V1",
    "ACTION_SPACE_VERSION_V2_PHASE1A",
    "ActionSpaceSpec",
    "DerivedChannel",
    "DerivedSurface",
    "FeasibilityCell",
    "ObservationContext",
    "ObservationSchema",
    "PolicyState",
    "RawScaleTensor",
    "ScaleSpec",
    "SplitArtifact",
    "SplitWindow",
    "TrajectoryBundle",
    "TrajectoryRecord",
    "TrajectorySpec",
    "TrajectoryStep",
    "WalkForwardFold",
    # policies
    "ACTION_SPACE_VERSION",
    "DERIVED_CHANNEL_TARGET_PLACEHOLDER",
    "DYNAMIC_TARGET_ASSET",
    "EXECUTION_INTENT_SCHEMA_VERSION",
    "ExecutionIntent",
    "InferenceArtifactExport",
    "LEGACY_POLICY_ARTIFACT_SCHEMA_VERSION",
    "JOINT_ACTION_VOCABULARY_VERSION_PHASE1A",
    "OBSERVATION_SCHEMA_VERSION",
    "POLICY_ARTIFACT_SCHEMA_VERSION",
    "POLICY_STATE_FEATURE_VERSION_PHASE1A",
    "STRICT_RUNTIME_CONTRACT_VERSION",
    "DerivedChannelTemplate",
    "ExecutorMetadata",
    "ExecutorPolicyExport",
    "OpaquePolicyPayload",
    "PolicyArtifact",
    "RuntimeMetadata",
    "StrictRuntimeContract",
    # registry
    "ComparisonReport",
    "ContinuityAuditSummary",
    "ContinuityCloseoutRecord",
    "CoverageStats",
    "PaperSimEvidenceRecord",
    "PromotionDecisionRecord",
    "PromotionEvidence",
    "RegistryIndex",
    "RegistryRecord",
    "ReproducibilityMetadata",
    "ScoreSnapshot",
    "SearchBudgetSummary",
    "SplitEvidence",
    # rewards
    "ActionReward",
    "RewardContext",
    "RewardEventSpec",
    "RewardSnapshot",
    "RewardTimeline",
    "VenueExecutionRef",
    # manifest (streaming path)
    "TRAJECTORY_STREAMING_FORMAT_VERSION",
    "TrajectoryManifest",
    "TrajectorySplitStats",
]
